apiVersion: v1
kind: Service
metadata:
  name: bus-service
  labels:
    app: bus-app
spec:
  selector:
    app: bus-app
  type: LoadBalancer
  ports:
  - name: http
    port: 9194
    targetPort: 9194
