server:
 port: 9192

spring:
 application:
    name: user-train-microservice
 datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: ${DB_PASSWORD:shubh123456}
    url: jdbc:mariadb://${MYSQL_HOST:localhost}:3307/userservice
    username: ${DB_USER:root}
 jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
 

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone:  ${EUREKA_SERVER:http://localhost:9190/eureka/}
debug: true 