server:
 port: 9191

spring:
 application:
    name: user-microservice
 data:
    mongodb:
      host: localhost
      port: 27017
      database: training
    
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone:  ${EUREKA_SERVER:http://localhost:9190/eureka/}
debug: true 
