server:
 port: 9194

spring:
 application:
    name: user-bus-microservice
 datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: ${DB_PASSWORD:shubh123456}
    url: ${JDBC_URL:jdbc:mariadb://training.c4nar1amqhye.us-east-1.rds.amazonaws.com:3306/userservice}
    username: ${DB_USER:admin}
 jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
 

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:9190/eureka
debug: true 
