apiVersion: v1
kind: Service
metadata:
  name: train-service
  labels:
    app: train-app
spec:
  selector:
    app: train-app
  type: LoadBalancer
  ports:
  - name: http
    port: 9192
    targetPort: 9192
