apiVersion: frontends/v1
kind: Deployment
metadata:
  name: frontend-deployment
   
spec:
  replicas: 1
  template:
    metadata:
      name: frontend-pod
      labels:
        frontend: frontend-app
    spec:
      containers:
        - name: frontend-container
          image: shubh1sinha/frontend-frontend-microservice:1.1
          imagePullPolicy: Always
          resources:
            limits:
              cpu: '50m'
              memory: '1G'
            requests:
              cpu: '1m'
              memory: '348Mi'
          ports:
          - containerPort: 9196
            name: http         
  selector:
    matchLabels:
     frontend: frontend-app